- include_tasks: patch-lbs.yml

- include_tasks: patch-masters.yml
  vars:
    master_hostname: "{{ groups.masters[0] }}"
    master_ip:  "{{ hostvars[groups['masters'][0]]['openshift_ip'] }}"
    command_master: "{{ groups.masters[1] }}"

- include_tasks: patch-masters.yml
  vars:
    master_hostname: "{{ groups.masters[1] }}"
    master_ip:  "{{ hostvars[groups['masters'][1]]['openshift_ip'] }}"
    command_master: "{{ groups.masters[2] }}"

- include_tasks: patch-masters.yml
  vars:
    master_hostname: "{{ groups.masters[2] }}"
    master_ip:  "{{ hostvars[groups['masters'][2]]['openshift_ip'] }}"
    command_master: "{{ groups.masters[0] }}"
