- name: Create patch directory on all hosts to store package lists
  file:
    path: /home/cloud-user/patching
    state: directory
    owner: cloud-user
    mode: 0755

- name: Write output of rpm -qa to file on all hosts
  shell: rpm -qa | sort > /home/cloud-user/patching/rpm-list-"{{ ansible_date_time.date }}"

- name: Register satellite var
  shell: subscription-manager status | grep "Overall Status" | awk '{ print $3 }'
  register: subscription_status
  become: true

- name: Fail if machines are not subscribed
  fail:
    msg: "Please ensure this machine has a valid subscription and re-run."
  when: subscription_status.stdout != 'Current'
