- name: Install haproxy
  yum:
    name: haproxy
    state: latest
- name: Configure haproxy
  template:
    src: templates/haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    force: yes
    backup: yes
- name: Update rsyslog config
  blockinfile:
    dest: /etc/rsyslog.conf
    create: yes
    block: |
      $ModLoad imudp
      $UDPServerRun 514
      $UDPServerAddress 127.0.0.1
      # Save haproxy logs to haproxy.log
      local2.* /var/log/haproxy.log
- name: Enable haproxy
  command: systemctl enable haproxy
- name: Restart haproxy
  command: systemctl restart haproxy
- name: Restart rsyslog
  command: systemctl restart rsyslog
- name: setup firewall - http
  firewalld:
    service: http
    immediate: true
    permanent: true
    zone: public
    state: enabled
  when: inventory_hostname in groups.loadbalancers_dataplane
- name: setup firewall - https
  firewalld:
    service: https
    immediate: true
    permanent: true
    zone: public
    state: enabled
  when: inventory_hostname in groups.loadbalancers_dataplane
- name: setup firewall - OpenShift API
  firewalld:
    port: 8443/tcp
    immediate: true
    permanent: true
    state: enabled
    zone: public
  when: inventory_hostname in groups.loadbalancers_controlplane
