- hosts: masters, localhost
  vars:
    datetime: "{{ ansible_date_time.date}}-{{ ansible_date_time.time }}"
  roles:
    - backup
 
- hosts: localhost
  vars:
    datetime: "{{ ansible_date_time.date}}-{{ ansible_date_time.time }}"
    ecs_transfer_status: "ecs_output.results[{{ item|int }}].failed"
  roles:
    - ecs
