---
- hosts: localhost
  tasks:
  - name: Generate admin password
    shell: openssl rand -base64 20 | cut -d= -f1
    register: new_admin_password_output

  - name: Generate user password
    shell: openssl rand -base64 20 | cut -d= -f1
    register: new_user_password_output

  - set_fact:
      new_admin_password: "{{ new_admin_password_output.stdout }}"
      new_user_password: "{{ new_user_password_output.stdout }}"

  - name: update passwords
    shell: |
      ansible-playbook --private-key ~/id_rsa_jenkins -i openshift-ansible-hosts -e USERNAME='admin' -e PASSWORD="{{ new_admin_password }}" tools/playbooks/htpassword.yaml
      ansible-playbook --private-key ~/id_rsa_jenkins -i openshift-ansible-hosts -e USERNAME='demo' -e PASSWORD="{{ new_user_password }}" tools/playbooks/htpassword.yaml

  - name: create text file
    shell: |
      echo "admin: {{ new_admin_password }})" > /home/cloud-user/passwords.txt;
      echo "demo: {{ new_user_password }}" > /home/cloud-user/passwords.txt
