- hosts: loadbalancers_controlplane
  vars:
    primary: "{{ groups.loadbalancers_controlplane[0] }}"
    vip: "{{ haproxy_vip }}"
  roles:
    - firewalld
    - keepalived
    - haproxy
    - squid
    - zabbix

- hosts: loadbalancers_internet_dataplane
  vars:
    primary: "{{ groups.loadbalancers_internet_dataplane[0] }}"
    vip: "{{ internet_vip }}"
  roles:
    - firewalld
    - keepalived
    - haproxy
    - zabbix

- hosts: loadbalancers_net2_dataplane
  vars:
    primary: "{{ groups.loadbalancers_net2_dataplane[0] }}"
    vip: "{{ net2_vip }}"
  roles:
    - firewalld
    - keepalived
    - haproxy
    - zabbix
