- import_playbook: upgrade_and_reboot_servers.yml
- import_playbook: loadbalancers.yml
- import_playbook: dns.yml
- import_playbook: all_servers.yml
- import_playbook: certbot.yml
- import_playbook: openshift.yml
# Commenting out upgrade_bastion playbook for now as there are package dependency issues causing pipeline failures.
#- import_playbook: upgrade_bastion.yml
