- name: Configure iptables on infra nodes for extra gateway
  iptables:
    chain: OS_FIREWALL_ALLOW
    protocol: tcp
    ctstate: NEW
    destination_port: "{{ item }}"
    jump: ACCEPT
    comment: Open port for extra gateway router
  with_items:
    - 7080
    - 7443
  when: extra_gateway_vip is defined and inventory_hostname in groups.nodes_infra

- name: Insert external service subnet into master-config.yaml
  replace:
    path: /etc/origin/master/master-config.yaml
    regexp: '^\s\s\-\s\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}\/\d{1,2}.*$'
    replace: '  - {{ external_service_subnet }}'
  when: inventory_hostname in groups.masters

- name: Restart master[0] services so config changes take effect
  shell: /usr/local/bin/master-restart {{ item }}
  with_items:
    - api
    - controllers
  when: inventory_hostname == groups.masters[0]

pause:
  seconds: 10

- name: Restart master[1] services so config changes take effect
  shell: /usr/local/bin/master-restart {{ item }}
  with_items:
    - api
    - controllers
  when: inventory_hostname == groups.masters[1]

pause:
  seconds: 10

- name: Restart master[2] services so config changes take effect
  shell: /usr/local/bin/master-restart {{ item }}
  with_items:
    - api
    - controllers
  when: inventory_hostname == groups.masters[2]
