- name: Configure iptables on infra nodes for extra gateway
  iptables:
    chain: OS_FIREWALL_ALLOW
    protocol: tcp
    ctstate: NEW
    destination_port: "{{ item }}"
    jump: ACCEPT
    comment: Open port for extra gateway router
  with_items:
    - 7080
    - 7443
  when: extra_gateway_vip is defined and inventory_hostname in groups.nodes_infra

- name: Configure iptables on infra nodes for secondary network
  iptables:
    chain: OS_FIREWALL_ALLOW
    protocol: tcp
    ctstate: NEW
    destination_port: "{{ item }}"
    jump: ACCEPT
    comment: Open port for secondary network router
  with_items:
    - 5080
    - 5443
  when: multinetwork and inventory_hostname in groups.nodes_infra

- name: Block root login via SSH to all instances
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^.?PermitRootLogin.*$'
    replace: 'PermitRootLogin no'
    backup: yes

- name: Reload sshd service to apply changes
  systemd:
    state: reloaded
    name: sshd
 
