- name: Configure iptables on infra nodes for extra gateway
  iptables:
    chain: OS_FIREWALL_ALLOW
    protocol: tcp
    ctstate: NEW
    destination_port: "{{ item }}"
    jump: ACCEPT
    comment: Open port for extra gateway router
  with_items:
    - 7080
    - 7443
  when: extra_gateway_vip is defined and inventory_hostname in groups.nodes_infra
  
- name: Make private-router iptables rules persistent
  blockinfile:
    path: /etc/sysconfig/iptables
    insertbefore: '^COMMIT'
    marker: "# {mark} private-router rules"
    block: |
      -A OS_FIREWALL_ALLOW -p tcp -m tcp --dport 7080 -m comment --comment "Open port for extra gateway router" -m conntrack --ctstate NEW -j ACCEPT
      -A OS_FIREWALL_ALLOW -p tcp -m tcp --dport 7443 -m comment --comment "Open port for extra gateway router" -m conntrack --ctstate NEW -j ACCEPT
  when: extra_gateway_vip is defined and inventory_hostname in groups.nodes_infra 

- name: Block root login via SSH to all instances
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^.?PermitRootLogin.*$'
    replace: 'PermitRootLogin no'
    backup: yes

- name: Reload sshd service to apply changes
  systemd:
    state: reloaded
    name: sshd

- name: Set journal size to 3G
  replace:
    path: /etc/systemd/journald.conf
    regexp: '^\sSystemMaxUse=.*'
    replace: ' SystemMaxUse=3G'
  when: inventory_hostname in groups.nodes and inventory_hostname not in groups.masters

- name: Restart systemd-journald service to implement journal size change
  service:
    name: systemd-journald
    state: restarted
  when: inventory_hostname in groups.nodes and inventory_hostname not in groups.masters

- include_tasks: cronjob-prep.yml
 
- include_tasks: squid-whitelist.yml
  when: multinetwork

- include_tasks: docker-prune.yml
