- name: Store whitelist serviceaccount token on Bastion
  lineinfile:
    dest: /home/cloud-user/whitelist-sa-token
    line: "{{ hostvars[groups.masters[0]]['whitelist_token']['stdout'] }}"
    state: present
    create: yes
  delegate_to: localhost
  run_once: yes

- name: Create a cron file for updating proxy whitelist for net2 deployments
  cron:
    name: "Update custom sites in Squid Whitelist"
    cron_file: proxy-whitelist
    minute: 0
    user: cloud-user
    job: "/usr/bin/ansible-playbook -i /usr/share/ansible/openshift-deployment-ansible/openshift-ansible-hosts /usr/share/ansible/openshift-deployment-ansible/tools/playbooks/squid-whitelist.yaml >> /home/cloud-user/cronjob-logs/proxy-whitelist.log 2>&1"
  become: true
  delegate_to: localhost
  run_once: yes
