- name: Install bind-utils
  yum:
    name: bind-utils
    state: latest
- name: Configure ansible hosts file
  template:
    src: templates/ansible-hosts-multimaster.j2
    dest: ./openshift-ansible-hosts
    force: yes
    backup: yes
