- name: Install bind-utils
  yum:
    name: bind-utils
    state: latest

- set_fact:
    admin_password: "{{ lookup('env', 'OPENSHIFT_PASSWORD') }}"

- name: Configure ansible hosts file
  template:
    src: templates/ansible-hosts-multimaster.j2
    dest: ./openshift-ansible-hosts
    force: yes
    backup: yes
