- name: Install bind-utils
  yum:
    name: bind-utils
    state: latest

- name: Download epel repo rpm
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel-release-latest-7.noarch.rpm

- name: Set permissions on downloaded rpm.
  file:
    path: /tmp/epel-release-latest-7.noarch.rpm
    mode: 0644

- name: Install epel repo
  yum:
    name: /tmp/epel-release-latest-7.noarch.rpm
    state: present
  become: yes
  become_method: sudo
  
- name: Remove epel file
  file:
    path: /tmp/epel-release-latest-7.noarch.rpm
    state: absent

- name: Install pip
  yum:
    name: python-pip
    state: latest
  become: yes

- name: Lock down epel repo to pip only
  lineinfile: 
    path: /etc/yum.repos.d/epel.repo
    insertafter: '^enabled=1'
    line: includepkgs=python2-pip*
  become: yes
  become_method: sudo

- name: Get list of installed packages
  yum:
    list=installed
  register: package_list

# package_list returns json array so json_query below is required to fish relevant data

- name: Get installed atomic-openshift-utils version
  set_fact:
    installed_version: "{{ package_list | json_query(package_filter) }}"
  vars: 
    package_filter: "results[?name=='openshift-ansible'].version"

- set_fact:
    admin_password: "{{ lookup('env', 'OPENSHIFT_PASSWORD') }}"

- name: Configure ansible hosts file
  template:
    src: templates/ansible-hosts-multimaster.j2
    dest: ./openshift-ansible-hosts
    force: yes
    backup: yes

