- name: Install bind-utils
  yum:
    name: bind-utils
    state: latest

- name: Get list of installed packages
  yum:
    list=installed
  register: package_list

# package_list returns json array so json_query below is required to fish relevant data

- name: Get installed atomic-openshift-utils version
  set_fact:
    installed_version: "{{ package_list | json_query(package_filter) }}"
  vars: 
    package_filter: "results[?name=='openshift-ansible'].version"

- set_fact:
    admin_password: "{{ lookup('env', 'OPENSHIFT_PASSWORD') }}"

- name: Configure ansible hosts file
  template:
    src: templates/ansible-hosts-multimaster.j2
    dest: ./openshift-ansible-hosts
    force: yes
    backup: yes
