---
- hosts: master-0.openstacklocal
  tasks:
    - fetch:
        src: /etc/origin/master/htpasswd
        dest: tmp/
- hosts: localhost
  vars:
    username: "{{ USERNAME }}"
    password: "{{ PASSWORD }}"
  tasks:
    - htpasswd:
        path: tmp/master-0.openstacklocal/etc/origin/master/htpasswd
        name: "{{ username }}"
        password: "{{ password }}"
        crypt_scheme: apr_md5_crypt
- hosts: masters
  tasks:
    - copy:
        src: tmp/master-0.openstacklocal/etc/origin/master/htpasswd
        dest: /etc/origin/master/htpasswd
- hosts: localhost
  tasks:
    - file:
        path: tmp/master-0.openstacklocal/
        state: absent
