# Modify the htpasswd file and replicate it
# across all master nodes

---
- hosts: masters[0]
  tasks:
    - fetch:
        src: /etc/origin/master/htpasswd
        dest: tmp/

- hosts: localhost
  vars:
    username: "{{ USERNAME }}"
    password: "{{ PASSWORD }}"
  tasks:
    - htpasswd:
        path: tmp/{{ groups.masters[0] }}/etc/origin/master/htpasswd
        name: "{{ username }}"
        password: "{{ password }}"
        crypt_scheme: apr_md5_crypt

- hosts: masters
  tasks:
    - copy:
        src: tmp/{{ groups.masters[0] }}/etc/origin/master/htpasswd
        dest: /etc/origin/master/htpasswd

- hosts: localhost
  tasks:
    - file:
        path: tmp/{{ groups.masters[0] }}/
        state: absent
