- hosts: nodes
  tasks:
  - name: Set journal size to 3G
    replace:
      path: /etc/systemd/journald.conf
      regexp: '^\s?SystemMaxUse=.*'
      replace: ' SystemMaxUse=3G'
    when: inventory_hostname not in groups.masters

  - name: Restart systemd-journald service to implement journal size change
    service:
      name: systemd-journald
      state: restarted
    when: inventory_hostname not in groups.masters
