---
- hosts: localhost, masters
  serial: 1
  tasks:
  - name: Update master-config.yaml 
    lineinfile:
      path: /etc/origin/master/master-config.yaml
      regexp: ^(?:\s+(-\s+name:\s+)?{{ item }}(\s+value:\s+|:\s+)?).*$
      line: test
      backup: yes
    with_items:
      - NO_PROXY
      - no_proxy
      - gitNoProxy
    when: inventory_hostname in groups.masters
    become: yes
    notify: 
      - restart master
    register: output

  - debug:
      var: output

  handlers:
  - name: restart master
    command: /usr/local/bin/master-restart "{{ item }}"
    with_items:
    - api
    - controllers
    retries: 5
    delay: 5
    register: result
    until: result.rc == 0
    notify: verify API server

  - name: verify API server
    command: >
      curl --tlsv1.2 --max-time 2
      --cacert /etc/origin/master/ca-bundle.crt
      https://{{ openshift_master_cluster_hostname }}:8443/healthz/ready
    args:
      warn: no
    register: l_api_available_output
    until: l_api_available_output.stdout == 'ok'
    retries: 120
    delay: 1
    changed_when: false
    
    #- include: /usr/share/ansible/openshift-ansible/playbooks/openstack/openshift-cluster/roles/openshift_cloud_provider/handlers/main.yml