---
- import_playbook: installPip.yaml

- hosts: localhost, loadbalancers_controlplane
  tasks:
  - name: Retrieve whitelist from ECS
    aws_s3:
      aws_access_key: "{{ s3accesskey }}"
      aws_secret_key: "{{ s3secretkey }}"
      s3_url: "https://{{ s3regionendpoint }}"
      bucket: "{{ s3bucketname }}"
      mode: get
      object: /squid/sites.whitelist.txt
      dest: /tmp/sites.whitelist.txt
    when: inventory_hostname == 'localhost'

  - name: Insert changed block to /etc/squid/sites.whitelist.txt
    blockinfile:
      block: "{{ lookup('file', '/home/cloud-user/sites.whitelist.txt') }}"
      path: /etc/squid/sites.whitelist.txt
      insertafter: EOF
      marker: "# {mark} ANSIBLE MANAGED BLOCK - User whitelisted domains #"
    become: yes
    when: inventory_hostname in groups.loadbalancers_controlplane
    notify:
      - reconfigure squid

  handlers:
    - name: reconfigure squid
      command: /usr/sbin/squid -k reconfigure
      become: yes
      when: inventory_hostname in groups.loadbalancers_controlplane