---
- hosts: localhost, loadbalancers_controlplane
  tasks:
  - name: Retrieve whitelist from config-map #Change this task to query API from the Bastion instead of Master
    command: /usr/local/bin/oc get configmaps proxy-whitelist -n default -o jsonpath='{.data.proxy-whitelist\.txt}'
    when: inventory_hostname in groups.masters[0] and multinetwork
    register: proxy_whitelist

  - name: Insert changed block to /etc/squid/sites.whitelist.txt
    blockinfile:
      block: "{{ hostvars[groups.masters[0]]['proxy_whitelist']['stdout'] }}"
      path: /etc/squid/sites.whitelist.txt
      insertafter: EOF
      marker: "# {mark} ANSIBLE MANAGED BLOCK - User whitelisted domains #"
    become: yes
    when: inventory_hostname in groups.loadbalancers_controlplane and multinetwork
    notify:
      - reconfigure squid

  handlers:
    - name: reconfigure squid
      command: /usr/sbin/squid -k reconfigure
      become: yes
      when: inventory_hostname in groups.loadbalancers_controlplane