---
- import_playbook: install-pip.yaml

- hosts: localhost, loadbalancers_controlplane, masters[0]
  tasks:
  - name: Retrieve whitelist from config-map
    command: /usr/local/bin/oc get configmaps proxy-whitelist -n default -o jsonpath='{.data.*}'
    when: inventory_hostname in groups.masters[0]
    register: proxy_whitelist

  - name: Insert changed block to /etc/squid/sites.whitelist.txt
    blockinfile:
      block: "{{ hostvars[groups.masters[0]]['proxy_whitelist']['stdout'] }}"
      path: /etc/squid/sites.whitelist.txt
      insertafter: EOF
      marker: "# {mark} ANSIBLE MANAGED BLOCK - User whitelisted domains #"
    become: yes
    when: inventory_hostname in groups.loadbalancers_controlplane
    notify:
      - reconfigure squid

  handlers:
    - name: reconfigure squid
      command: /usr/sbin/squid -k reconfigure
      become: yes
      when: inventory_hostname in groups.loadbalancers_controlplane