- name: Send backed up files to bucket in ECS
  aws_s3:
    aws_access_key: "{{ s3accesskey }}"
    aws_secret_key: "{{ s3secretkey }}"
    s3_url: "https://{{ s3regionendpoint }}"
    bucket: "{{ s3bucketname }}"
    object: "{{ item }}"
    src: "{{ item }}"
    mode: put
    rgw: true
  with_fileglob:
    - "/home/cloud-user/backups/*"
