- name: Backup etcd data dir
  shell: docker exec etcd_container etcdctl backup --data-dir /var/lib/etcd --backup-dir /var/lib/etcd.bak
  become: yes
  when: inventory_hostname == groups.masters[0]

- name: Backup etcd db
  shell: docker exec etcd_container cp /var/lib/etcd/member/snap/db /var/lib/etcd.bak/member/snap/db
  become: yes
  when: inventory_hostname == groups.masters[0]

- name: Copy backup files from container to host
  shell: docker cp etcd_container:/var/lib/etcd.bak /home/cloud-user/etcd.bak
  become: yes
  when: inventory_hostname == groups.masters[0]

- name: Clean up backup file in container
  shell: docker exec etcd_container rm -rf /var/lib/etcd.bak
  become: yes
  when: inventory_hostname == groups.masters[0]

- name: Change permissions of backup
  file:
    path: /home/cloud-user/etcd.bak
    owner: cloud-user
    group: cloud-user
  become: yes
  when: inventory_hostname == groups.masters[0]

- name: tar etcd backup
  archive:
    path: /home/cloud-user/etcd.bak
    dest: /home/cloud-user/etcd-data.bak.tar
    format: tar
  when: inventory_hostname == groups.masters[0]

- name: Fetch tar file back to bastion
  fetch:
    src: /home/cloud-user/etcd.bak.tar
    dest: /home/cloud-user/backups/etcd-data.bak.tar-{{ datetime }}
    flat: yes
  when: inventory_hostname == groups.masters[0]

- name: Clean up file from master
  command: rm -rf /home/cloud-user/{{ item }}
  with_items:
    - etcd.bak
    - etcd-data.bak.tar
  become: true
  when: inventory_hostname == groups.masters[0]

- name: Backup etcd config on all masters
  archive:
    path: /etc/etcd
    dest: /home/cloud-user/etcd-config-{{ ansible_hostname }}.tar
    format: tar
    owner: cloud-user
    group: cloud-user
  when: inventory_hostname in groups.masters

- name: Fetch tar files back to bastion
  fetch:
    src: /home/cloud-user/etcd-config-{{ ansible_hostname }}.tar
    dest: /home/cloud-user/backups/etcd-config-{{ ansible_hostname }}-{{ datetime }}.tar
    flat: yes
  when: inventory_hostname in groups.masters

- name: Remove tar files from masters
  file:
    path: /home/cloud-user/etcd-config-{{ ansible_hostname }}.tar
    state: absent
  when: inventory_hostname in groups.masters
