- name: Create backups directory
  file:
    path: /home/cloud-user/backups
    state: directory
    mode: 0755
  when: inventory_hostname == 'localhost'

- include_tasks: etcd-3-11.yml
  when: openshiftVersion == "3.11"

- include_tasks: etcd-3-10.yml
  when: openshiftVersion == "3.10"

- include_tasks: etcd-3-9.yml
  when: openshiftVersion == 3.9

- include_tasks: masters-3-11.yml
  when: openshiftVersion == "3.11"

- include_tasks: masters-3-10.yml
  when: openshiftVersion == "3.10"

- include_tasks: masters-3-9.yml
  when: openshiftVersion == 3.9
