- name: Copy /etc/origin/master directory and tar it
  archive:
    path: /etc/origin/master
    dest: /home/cloud-user/master.tar
    format: tar
  when: inventory_hostname == groups.masters[0]

- name: Copy /etc/etcd/ca directory and tar it
  archive:
    path: /etc/etcd/
    dest: /home/cloud-user/etcd.tar
    format: tar
  when: inventory_hostname == groups.masters[0]

- name: Fetch tar files back to bastion (master)
  fetch: 
    src: /home/cloud-user/master.tar
    dest: /home/cloud-user/master.tar
    flat: yes
  when: inventory_hostname == groups.masters[0]

- name: Fetch tar files back to bastion (etcd)
  fetch:
    src: /home/cloud-user/etcd.tar
    dest: /home/cloud-user/etcd.tar
    flat: yes
  when: inventory_hostname == groups.masters[0]
