- name: Copy /etc/origin/master directory and tar it
  archive:
    path: /etc/origin/master
    dest: /home/cloud-user/master.tar
    format: tar
  when: inventory_hostname == groups.masters[0]

- name: Fetch tar file back to bastion (master)
  fetch:
    src: /home/cloud-user/master.tar
    dest: /home/cloud-user/master.tar
    flat: yes
  when: inventory_hostname == groups.masters[0]

- name: tar deployment code directory
  archive:
    path: /usr/share/ansible/openshift-deployment-ansible
    dest: /home/cloud-user/deployment-code.tar
    format: tar
  when: inventory_hostname == 'localhost'

- name: Send master tar file back to bucket in S3
  aws_s3:
    aws_access_key: "{{ s3accesskey }}"
    aws_secret_key: "{{ s3secretkey }}"
    s3_url: "https://{{ s3regionendpoint }}"
    bucket: "{{ s3bucketname }}"
    object: "/backups/master.tar-{{ ansible_date_time.date }}"
    src: "/home/cloud-user/master.tar"
    mode: put
    rgw: true
  when: inventory_hostname == 'localhost'

- name: Send ansible deployment code tar file back to bucket in S3
  aws_s3:
    aws_access_key: "{{ s3accesskey }}"
    aws_secret_key: "{{ s3secretkey }}"
    s3_url: "https://{{ s3regionendpoint }}"
    bucket: "{{ s3bucketname }}"
    object: "/backups/deployment-code.tar-{{ ansible_date_time.date }}"
    src: "/home/cloud-user/deployment-code.tar"
    mode: put
    rgw: true
  when: inventory_hostname == 'localhost'

- name: Clean up tar file from master
  command: rm -f /home/cloud-user/master.tar
  become: true
  when: inventory_hostname == groups.masters[0]
    
