- name: Create whitelist project
  command: /usr/local/bin/oc new-project whitelist

- name: Create proxy-whitelist configmap and create empty key
  command: /usr/local/bin/oc create configmap proxy-whitelist --from-literal=proxy-whitelist.txt= -n whitelist

- name: Create whitelist-reader serviceaccount
  command: /usr/local/bin/oc create sa whitelist-reader -n whitelist

- name: Create read-whitelist role
  command: /usr/local/bin/oc create role read-whitelist --verb=get,list --resource=configmaps --resource-name=proxy-whitelist -n whitelist

- name: Apply read-whitelist role to whitelist-reader serviceaccount
  command: /usr/local/bin/oc policy add-role-to-user read-whitelist -z whitelist-reader -n whitelist --role-namespace='whitelist'

- name: Get whitelist-reader serviceaccount token name
  command: /usr/local/bin/oc get sa -n whitelist -o jsonpath='{$.items[?(@.metadata.name=="whitelist-reader")].secrets[0].name}'
  register: whitelist_token_name

- name: Extract base64 whitelist-reader token
  command: /usr/local/bin/oc get secret {{ whitelist_token_name.stdout }} -n whitelist -o jsonpath='{$.data.token}'
  register: whitelist_token_b64