- name: Create whitelist project
  command: /usr/local/bin/oc new-project whitelist

- name: Create proxy-whitelist configmap and create empty key
  command: /usr/local/bin/oc create configmap proxy-whitelist --from-literal=proxy-whitelist.txt= -n whitelist

- name: Create whitelist-reader serviceaccount
  command: /usr/local/bin/oc create sa whitelist-reader -n whitelist

- name: Create read-whitelist role
  command: /usr/local/bin/oc create role read-whitelist --verb=get,list --resource=configmaps --resource-name=proxy-whitelist -n whitelist

- name: Apply read-whitelist role to whitelist-reader serviceaccount
  command: /usr/local/bin/oc policy add-role-to-user read-whitelist -z whitelist-reader -n whitelist --role-namespace='whitelist'

- name: Get first whitelist-reader serviceaccount token
  shell: /usr/local/bin/oc get secrets -o jsonpath='{$.items[?(@.metadata.annotations.kubernetes\.io/service-account\.name=="whitelist-reader")].data.token}' -n whitelist | /usr/bin/awk '{print $1}'
  register: whitelist_token_b64
