- name: Enable optional and extras repos
  command: subscription-manager repos --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-optional-rpms
- name: Download file
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel-release-latest-7.noarch.rpm
- file:
    path: /tmp/epel-release-latest-7.noarch.rpm
    mode: 0777
- name: Install epel repo
  yum:
    name: /tmp/epel-release-latest-7.noarch.rpm
    state: present
  become: yes
  become_method: sudo
- name: Install certbot
  yum:
    name: certbot
    state: latest
- name: Stop HAProxy
  command: systemctl stop haproxy
- name: Run certbot
  command: certbot -h
- name: Start HAProxy
  command: systemctl start haproxy
