- name: setup forwarder config 
  blockinfile:
    block: "{{ lookup('template', 'templates/forwarder_zone_config.j2') }}"
    dest: "/etc/named.conf"
    backup: yes
  when: inventory_hostname in groups.dns_net2
- name: Set corect selinux permissions
  seboolean:
    name: named_write_master_zones
    state: yes
    persistent: yes
  when: inventory_hostname in groups.dns_net2
- name: Restart bind
  systemd:
    name: named
    state: restarted
  when: inventory_hostname in groups.dns_net2
