- name: Install squid
  yum:
    name: squid
    state: latest
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: Configure squid
  template:
    src: templates/squid.j2
    dest: /etc/squid/squid.conf
    force: yes
    backup: yes
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: Setup whitelist file
  copy:
    dest: /etc/squid/sites.whitelist.txt
    content: |
        registry.access.redhat.com
        registry.redhat.io
    backup: yes
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: setup firewall - squid
  firewalld:
    port: 3128/tcp
    immediate: true
    permanent: true
    state: enabled
    zone: public
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: enable and start the squid service
  systemd:
    name: squid
    state: started
    enabled: yes
  when: inventory_hostname in groups.loadbalancers_controlplane
