- name: Install squid
  yum:
    name: squid
    state: latest
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: Configure squid
  template:
    src: templates/squid.j2
    dest: /etc/squid/squid.conf
    force: yes
    backup: yes
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: Setup whitelist file
  template:  
    src: templates/whitelist.j2
    dest: /etc/squid/sites.whitelist.txt
    force: yes
    backup: yes
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: Insert ansible marker
  lineinfile:
    path: /etc/squid/sites.whitelist.txt
    insertbefore: BOF
    line: '# BEGIN ANSIBLE MANAGED BLOCK - Whitelisted domains #'

- name: Insert ansible marker
  lineinfile:
    path: /etc/squid/sites.whitelist.txt
    insertafter: EOF
    line: '# END ANSIBLE MANAGED BLOCK - Whitelisted domains #'


- name: setup firewall - squid
  firewalld:
    port: 3128/tcp
    immediate: true
    permanent: true
    state: enabled
    zone: public
  when: inventory_hostname in groups.loadbalancers_controlplane

- name: enable and start the squid service
  systemd:
    name: squid
    state: started
    enabled: yes
  when: inventory_hostname in groups.loadbalancers_controlplane
